server:
  port: 9090

pufvault:
  cors:
    allowedOrigins:
      - "http://127.0.0.1:5500"
      - "http://localhost:5500"
      - "https://www.domenicoamelino.com"

  serial:
    port: "auto"
    baud: 115200
    timeoutMs: 3000

  users:
    - username: "demo"
      password: "demo123"
      userId: "user001"
      maxSlots: 3
      animationEnabled: false

    - username: "test"
      password: "test123"
      userId: "test001"
      maxSlots: 2
      animationEnabled: true